import '@ant-design/v5-patch-for-react-19';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from 'antd';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider
    theme={{
      components: {
        Checkbox: {
          colorText: "#FFFFFF",
          colorPrimary: "#262626",
          colorPrimaryHover: "#262626",
          colorBorder: "#FFFFFF",
        },
        Radio: {
          colorPrimary: "#262626",
          colorText: "#FFFFFF",
        },
        Card: {
          colorTextHeading: "#FFFFFF",
          colorBgContainer: "#424242",
        },
        Select: {
          optionSelectedBg: "#262626",
          colorBgElevated: "#424242",
          colorText: "#FFFFFF",
          colorBgContainer: "#262626",
          hoverBorderColor: "#424242",
          activeBorderColor: "#424242",
        },
        Input: {
          colorText: "#FFFFFF",
          activeBg: "#262626",
          addonBg: "#262626",
          activeBorderColor: "#424242",
          hoverBorderColor: "#424242",
          colorBgContainer: "#262626",
        },
        Button: {
          defaultHoverBorderColor: "#424242",
        }
      },
    }}
  >
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    </ConfigProvider>
  );
}
